### GET ALL Categories
GET http://localhost:3000/api/categories
Accept: application/json

### CREATE New Category
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
    "name" : "Book"
}

### GET Category By Id
GET http://localhost:3000/api/categories/1
Accept: : application/json

### UPDATE Category By Id
PUT http://localhost:3000/api/categories/1
Accept: application/json
Content-Type: application/json

{
    "name" : "Food"
}

### DELETE Category By Id
PUT http://localhost:3000/api/categories/1
Accept: application/json



# ***********************************
# ===== ERROR TEST ======
# ***********************************

### ERROR GET Category By Id (404 NOT FOUND)
GET http://localhost:3000/api/categories/100
Accept: : application/json

### ERROR UPDATE Category By Id (400 BAD REQUEST) Validation Fail
PUT http://localhost:3000/api/categories/2
Accept: application/json
Content-Type: application/json

{
    "name" : ""
}

### ERROR GET Category By Id (500 Internal Server Error)